name: ChinguCD

on:
  # Trigger this workflow when a updates to main are merged from a PR or
  # made directly via a push
  push:
    branches:
      - main

jobs:
  eslint:
    name: chingucd
    runs-on: ubuntu-latest

    steps:
      # Setup & initialization
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # You can specify the Node.js version required for your project

      - name: Install dependencies
        run: npm install

      # Run integration tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      # Deploy a preview to Netlify
      # Based on https://github.com/marketplace/actions/netlify-deploy
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        id: deploypreview
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: "dist"
          NETLIFY_DEPLOY_TO_PROD: true
     
      # Add the Netlify deployment info
      # Base on https://github.com/marketplace/actions/comment-pull-request
      - name: Comment PR with execution number
        run: |
          echo **__Netlify Preview Deployment Summary:__**
          echo ${{ env.NETLIFY_OUTPUT }}