name: DeployProd

on: 
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    name: DeployProd
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Starting deployment to Production...'
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: "dist"