name: IncrSemver

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    branches-ignore:
      - development
jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: IncrSemver
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Starting increment of semver...'
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: darioblanco/bump-semver@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}